version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  main:
    jobs:
      - node/test:
          filters:
            branches:
              ignore:
                - main
      - vercel:
          filters:
            branches:
              only:
                - main
      - npm:
          filters:
            tags:
              only:
                - /v[0-9]+(\.[0-9]+)*/

jobs:
  vercel:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build static site
          command: npm run build
      - run:
          name: Prepare Vercel project.json
          command: |
            mkdir .vercel
            echo $VERCEL_PROJECT_JSON > .vercel/project.json
      - run:
          name: Deploy Vercel production
          command: npx vercel --prod --token $VERCEL_TOKEN
  npm:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build npm package
          command: npm run build:npm
      - run:
          name: Npm publish
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm version
            npm publish
